### ISSUE TITLE
sqlTransformer don't support split function

### ISSUE THREAD

**Issue by lumingfeihs** [jpmml/jpmml-sparkml#102]
hello,I have the following problem:
```
Exception in thread "main" java.lang.IllegalArgumentException: Spark SQL function 'split(ctype#1340, \|)' (class org.apache.spark.sql.catalyst.expressions.StringSplit) is not supported
	at org.jpmml.sparkml.ExpressionTranslator.translateInternal(ExpressionTranslator.java:467)
	at org.jpmml.sparkml.ExpressionTranslator.translateInternal(ExpressionTranslator.java:247)
	at org.jpmml.sparkml.ExpressionTranslator.translate(ExpressionTranslator.java:91)
	at org.jpmml.sparkml.ExpressionTranslator.translate(ExpressionTranslator.java:86)
	at org.jpmml.sparkml.feature.SQLTransformerConverter.encodeFeatures(SQLTransformerConverter.java:110)
	at org.jpmml.sparkml.feature.SQLTransformerConverter.registerFeatures(SQLTransformerConverter.java:141)
	at org.jpmml.sparkml.PMMLBuilder.build(PMMLBuilder.java:114)
	at org.jpmml.sparkml.model.PMMLModelSave.save(PMMLModelSave.scala:115)
	at org.jpmml.sparkml.model.PMMLModelSave.save(PMMLModelSave.scala:123)
```

How do I get split？

**Comment by vruusmann** [comment]
> How do I get split？

The PMML standard (as of the 4.4. schema version) does not define a `split` built-in function.

What do you need those text tokens for? Depending on the answer, there might workaround available.

For example, see a relevant discussion (counting words in a sentence): https://github.com/jpmml/sklearn2pmml/issues/259
