### ISSUE TITLE
java.lang.NoSuchMethodError on org.dmg.pmml.MiningField.setUsageType

### ISSUE THREAD

**Issue by thetuxedo** [jpmml/jpmml-sparkml#12]
Dear Sir or Madam,
When I try to export my model, I encounter following error.
I am using the jpmml-sparkml 1.1.6, and spark 2.0.2

```
scala> val pmml = ConverterUtil.toPMML(df.schema, model)
java.lang.NoSuchMethodError: org.dmg.pmml.MiningField.setUsageType(Lorg/dmg/pmml/MiningField$UsageType;)Lorg/dmg/pmml/MiningField;
  at org.jpmml.converter.ModelUtil.createMiningField(ModelUtil.java:73)
  at org.jpmml.converter.ModelUtil.createMiningSchema(ModelUtil.java:57)
  at org.jpmml.converter.ModelUtil.createMiningSchema(ModelUtil.java:46)
  at org.jpmml.sparkml.model.RandomForestClassificationModelConverter.encodeModel(RandomForestClassificationModelConverter.java:45)
  at org.jpmml.sparkml.model.RandomForestClassificationModelConverter.encodeModel(RandomForestClassificationModelConverter.java:33)
  at org.jpmml.sparkml.ConverterUtil.toPMML(ConverterUtil.java:131)
  ... 52 elided
```
Thanks in advance for helping.

**Comment by vruusmann** [comment]
You need to configure your application classpath properly.

JPMML-SparkML version 1.1.6 is compiled against JPMML-Model version 1.3.4 (via JPMML-Converter version 1.2.1). However, Apache Spark version 2.0.X contains JPMML-Model version 1.2.15, which then "shadows" the proper version:
https://issues.apache.org/jira/browse/SPARK-15526

Perhaps you should be using the [JPMML-SparkML-Package](https://github.com/jpmml/jpmml-sparkml-package) library instead of the "raw" [JPMML-Spark](https://github.com/jpmml/jpmml-sparkml) library? If you're determined to roll on your own, then at least take a look at its `pom.xml` file for proper application packaging workflow:
https://github.com/jpmml/jpmml-sparkml-package/blob/master/pom.xml#L39
