### ISSUE TITLE
Error with LightGBMClassificationModel

### ISSUE THREAD

**Issue by davidmcomfort** [jpmml/jpmml-sparkml#126]
I keep getting an error when trying to convert Pipeline models built using SynapseML LightGBM. I am using Databricks runtime 10.4 LTS ML (includes Apache Spark 3.2.1, Scala 2.12) and org.jpmml:pmml-sparkml:2.2.0 and com.microsoft.azure:synapseml_2.12:0.9.5 installed as libraries. I can get Random Forest and Decision Tree classifiers converted.

```
import com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassificationModel
import org.apache.spark.ml.Pipeline
import org.apache.spark.ml.classification.DecisionTreeClassifier
import org.apache.spark.ml.feature.RFormula

val irisData = spark.read.format("csv").option("header", "true").option("inferSchema", "true").load("dbfs:/FileStore/Iris.csv")
val irisSchema = irisData.schema

val rFormula = new RFormula().setFormula("Species ~ .")
// val dtClassifier = new DecisionTreeClassifier().setLabelCol(rFormula.getLabelCol).setFeaturesCol(rFormula.getFeaturesCol)
val dtClassifier = new LightGBMClassificationModel().setFeaturesCol(rFormula.getFeaturesCol).setActualNumClasses(3)
val pipeline = new Pipeline().setStages(Array(rFormula, dtClassifier))

val pipelineModel = pipeline.fit(irisData)
import org.jpmml.sparkml.PMMLBuilder

val pmml = new PMMLBuilder(irisSchema, pipelineModel).build()
```

And the error I get is:
```
IllegalArgumentException: Transformer class com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassificationModel is not supported
	at org.jpmml.sparkml.ConverterFactory.newConverter(ConverterFactory.java:60)
	at org.jpmml.sparkml.PMMLBuilder.build(PMMLBuilder.java:111)
	at $line6517e63f9ee64c1faf3facb63ea60bcc29.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-868486667367686:3)
	at $line6517e63f9ee64c1faf3facb63ea60bcc29.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-868486667367686:51)
	at $line6517e63f9ee64c1faf3facb63ea60bcc29.$read$$iw$$iw$$iw$$iw.<init>(command-868486667367686:53)
	at $line6517e63f9ee64c1faf3facb63ea60bcc29.$read$$iw$$iw$$iw.<init>(command-868486667367686:55)
	at $line6517e63f9ee64c1faf3facb63ea60bcc29.$read$$iw$$iw.<init>(command-868486667367686:57)
	at $line6517e63f9ee64c1faf3facb63ea60bcc29.$read$$iw.<init>(command-868486667367686:59)
	at $line6517e63f9ee64c1faf3facb63ea60bcc29.$read.<init>(command-868486667367686:61)
	at $line6517e63f9ee64c1faf3facb63ea60bcc29.$read$.<init>(command-868486667367686:65)
	at $line6517e63f9ee64c1faf3facb63ea60bcc29.$read$.<clinit>(command-868486667367686)
	at $line6517e63f9ee64c1faf3facb63ea60bcc29.$eval$.$print$lzycompute(<notebook>:7)
	at $line6517e63f9ee64c1faf3facb63ea60bcc29.$eval$.$print(<notebook>:6)
	at $line6517e63f9ee64c1faf3facb63ea60bcc29.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:747)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1020)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:568)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:36)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:116)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:567)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:594)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:564)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:219)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:225)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:999)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:952)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:225)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$12(DriverLocal.scala:631)
	at com.databricks.logging.Log4jUsageLoggingShim$.$anonfun$withAttributionContext$1(Log4jUsageLoggingShim.scala:33)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:94)
	at com.databricks.logging.Log4jUsageLoggingShim$.withAttributionContext(Log4jUsageLoggingShim.scala:31)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:205)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:204)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:59)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:240)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:225)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:59)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:608)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:615)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:607)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommandAndGetError(DriverWrapper.scala:526)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:561)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:431)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:374)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:225)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vruusmann** [comment]
Does your project include the `org.jpmml:pmml-sparkml-lightgbm` dependency? This is where the converters for `com.microsoft.azure.synapse.ml.lightgbm.*`estimator classes reside.

**Comment by davidmcomfort** [comment]
> Does your project include the `org.jpmml:pmml-sparkml-lightgbm` dependency? This is where the converters for `com.microsoft.azure.synapse.ml.lightgbm.*`estimator classes reside.

Thanks for the fast response. No, it doesn't. I will add now. It wasn't clear that it was needed. Thanks!

**Comment by davidmcomfort** [comment]
I install `org.jpmml:pmml-sparkml-lightgbm:2.2.0` but I still get an error even when trying to convert a simple decision tree classifier:

**Comment by vruusmann** [comment]
> > Does your project include the org.jpmml:pmml-sparkml-lightgbm dependency?
>
> No, it doesn't. It wasn't clear that it was needed.

The idea is that if some piece of conversion functionality is dependent on external libraries, then it's "isolated" into a separate JPMML-SparkML module. For example, `pmml-sparkml-lightgbm` and `pmml-sparkml-xgboost`.

The third party library for LightGBM support is 3-5X bigger than the JPMML-SparkML library itself, and probably does include some JNI libraries (ie. is operating system/platform dependent). So, it doesn't make sense to include it by default.

**Comment by vruusmann** [comment]
@davidmcomfort I can see in my e-mail inbox that you've added some interesting technical comments to this thread overnight, but have deleted them afterwards.

Modifying issue/project history is not a particularly polite behaviour. It will get you blocked next time.

**Comment by davidmcomfort** [comment]
My Apologies. I was able to get both Scala and Pyspark versions working so I can convert SynapseML LightGBM models to PMML. The setup I am using is Databrick Runtime `10.4 LTS ML (includes Apache Spark 3.2.1, Scala 2.12)` with the `org.jpmml:pmml-sparkml:2.2.0`, `com.microsoft.azure:synapseml_2.12:0.9.5`, `org.jpmml:pmml-sparkml-lightgbm:2.2.0` libraries installed.

An code example is:
```
%scala
import com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassifier
import org.apache.spark.ml.Pipeline
import org.apache.spark.ml.feature.RFormula

val irisData = spark.read.format("csv").option("header", "true").option("inferSchema", "true").load("dbfs:/FileStore/Iris_2_classes.csv")
val irisSchema = irisData.schema

val rFormula = new RFormula().setFormula("Species ~ .")
val dtClassifier = new LightGBMClassifier().setFeaturesCol(rFormula.getFeaturesCol)
val pipeline = new Pipeline().setStages(Array(rFormula, dtClassifier))

val pipelineModel = pipeline.fit(irisData)

import org.jpmml.sparkml.PMMLBuilder

val pmml = new PMMLBuilder(irisSchema, pipelineModel).build()

import javax.xml.transform.stream.StreamResult
import org.jpmml.model.JAXBUtil

JAXBUtil.marshalPMML(pmml, new StreamResult(System.out))
```
And in Pyspark:
```
!pip install pyspark2pmml
from pyspark.ml import Pipeline
from pyspark.ml.classification import DecisionTreeClassifier
from pyspark.ml.feature import RFormula

df = spark.read.csv("dbfs:/FileStore/Iris_2_classes.csv", header = True, inferSchema = True)

formula = RFormula(formula = "Species ~ .")

from synapse.ml.lightgbm import LightGBMClassifier
classifier = LightGBMClassifier()
pipeline = Pipeline(stages = [formula, classifier])
pipelineModel = pipeline.fit(df)

from pyspark2pmml import PMMLBuilder
pmmlBuilder = PMMLBuilder(sc, df, pipelineModel)

pmmlBuilder.buildFile("/dbfs/FileStore/LightGBMClassificationIris_v2.pmml")
```
I would like to write to a S3 Bucket, but haven't been able to do that yet.
Thanks again for your help.
