### ISSUE TITLE
Float not supported by SparkMLEncoder

### ISSUE THREAD

**Issue by reeseb777** [jpmml/jpmml-sparkml#13]
The code appears to accept only fields of data type String, Integer, Double, or Boolean.

My use case includes float columns and generates the exception below:

```
Caused by: java.lang.IllegalArgumentException: Expected string, integral, double or boolean type, got float type
	at org.jpmml.sparkml.SparkMLEncoder.createDataField(SparkMLEncoder.java:303)
	at org.jpmml.sparkml.SparkMLEncoder.getFeatures(SparkMLEncoder.java:232)
	at org.jpmml.sparkml.feature.VectorAssemblerConverter.encodeFeatures(VectorAssemblerConverter.java:43)
	at org.jpmml.sparkml.SparkMLEncoder.append(SparkMLEncoder.java:74)
	at org.jpmml.sparkml.ConverterUtil.toPMML(ConverterUtil.java:123)
```

**Comment by vruusmann** [comment]
Reproducible example? I'm not aware of any built-in Apache Spark ML transformation or model types that would prefer `float` over `double`. In fact, if you feed `float` values into pipeline, then the first step will automatically promote them to `double` values.

As a workaround, why don't you do the type cast manually?

**Comment by reeseb777** [comment]
Creating a Schema that duplicates the original Schema, except replacing each `float` StructField with a `double` StructField, and passing this new Schema into ConverterUtil.toPMML() was successful as a workaround.

**Comment by vruusmann** [comment]
Indeed, the above is a technically viable workaround, as the `ConverterUtil#toPMML(StructType, PipelineModel)` method has no way of knowing/verifying if the first argument is a real or synthetic schema descriptor. 

However, you need to be aware that by doing so, you run the risk of losing some numerical precision between Apache Spark ML and PMML predictions.
