### ISSUE TITLE
java.lang.NoClassDefFoundError: org/dmg/pmml/mining/MiningModel

### ISSUE THREAD

**Issue by manugarri** [jpmml/jpmml-sparkml#15]
Im testing jpmml-spark on the spark-shell. We are running it on top of Yarn, using Spark 2.0.1 and scala 2.11.

I built the jar for the package and start the session like : 

```$SPARK_HOME/bin/spark-shell --jars  jpmml-sparkml-1.1-SNAPSHOT.jar --packages com.databricks:spark-avro_2.11:3.0.1 --master yarn --deploy-mode client```

However, I get an error when exporting a pipeline toPMMLByteArray.

```
import org.jpmml.sparkml.ConverterUtil

.... all of  the code to create the pipeline

val sparkPipelinePMMLEstimator = new Pipeline().setStages( categoricalFeatureIndexers.union(categoricalFeatureOneHotEncoders.union(Seq(featureAssemblerLr, featureAssemblerRf) )) :+ randomForest)

val sparkPipelinePMML = sparkPipelinePMMLEstimator.fit(df)
val pmmlBytes = org.jpmml.sparkml.ConverterUtil.toPMMLByteArray(df.schema, sparkPipelinePMML)
```

This fails with the following error:

```
scala> val pmmlBytes = org.jpmml.sparkml.ConverterUtil.toPMMLByteArray(df.schema, sparkPipelinePMML)
java.lang.NoClassDefFoundError: org/dmg/pmml/mining/MiningModel
  ... 48 elided
Caused by: java.lang.ClassNotFoundException: org.dmg.pmml.mining.MiningModel
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 48 more
```

Which seems like there is a package `org.dmg.pmml.mining` missing. How can I fix this issue?

**Comment by manugarri** [comment]
ok, nevermind. I think that the only way to use PMML in spark is by using the [spark package](https://github.com/jpmml/jpmml-sparkml-package)
