### ISSUE TITLE
mvn: Importing the multiarray numpy extension module failed

### ISSUE THREAD

**Issue by mrjoseph84** [jpmml/jpmml-sparkml#23]
When I try to build a **jpmml-sparkml** package with pyspark profile:
`mvn -Ppyspark clean package`

I am getting an error:
```
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from jpmml_sparkml import __license__, __version__
  File "/home/bluedata/jpmml-sparkml-package/target/egg-sources/jpmml_sparkml/__init__.py", line 4, in <module>
    from pyspark.ml.common import _py2java
  File "/usr/lib/spark/spark-2.1.1-bin-hadoop2.7/python/pyspark/ml/__init__.py", line 22, in <module>
    from pyspark.ml.base import Estimator, Model, Transformer
  File "/usr/lib/spark/spark-2.1.1-bin-hadoop2.7/python/pyspark/ml/base.py", line 21, in <module>
    from pyspark.ml.param import Params
  File "/usr/lib/spark/spark-2.1.1-bin-hadoop2.7/python/pyspark/ml/param/__init__.py", line 26, in <module>
    import numpy as np
  File "/usr/lib64/python3.4/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib64/python3.4/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib64/python3.4/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib64/python3.4/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib64/python3.4/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: **cannot import name multiarray**

[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.jav
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

My PYTHONPATH variable:
`/usr/lib64/python3.4/site-packages:/usr/lib/spark/spark-2.1.1-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip:/usr/lib/spark/spark-2.1.1-bin-hadoop2.7/python/:/opt/bluedata/vagent/vagent/python:/opt/bluedata/vagent/vagent/python`

I uninstalled numpy (numpy-1.13.0) and installed again - no progress.

This error does not appear when I build without pyspark profile:
`mvn clean package`
However, no EGG file is created and when I try to run a code from Zeppelin:

```
from jpmml_sparkml import toPMMLBytes
pmmlBytes = toPMMLBytes(sc, vectorized_CV_data, CV_model)
print(pmmlBytes.decode("UTF-8"))
```
I am getting:
`Traceback (most recent call last): File "/tmp/zeppelin_pyspark-1803236182413842559.py", line 337, in <module> exec(code) File "<stdin>", line 1, in <module> ImportError: No module named 'jpmml_sparkml' `

Any help on how to solve this issue would be appreciated.

Thanks, Michal

**Comment by vruusmann** [comment]
It is now possible to build the JPMML-SparkML-Package EGG file even if there is no local copy of Apache Spark available.

> Original error was: **cannot import name multiarray**

Your Numpy (or Python) installation is broken. This message has got nothing to do with JPMML-SparkML and/or PySpark.

**Comment by mrjoseph84** [comment]
Other packages work correctly - this applies also to numpy.
However, when I am trying to build the  JPMML-SparkML-Package I am getting:

```
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from jpmml_sparkml import __license__, __version__
  File "/home/bluedata/jpmml-sparkml-package/target/egg-sources/jpmml_sparkml/__init__.py", line 4, in <module>
    from pyspark.ml.common import _py2java
  File "/usr/lib/spark/spark-2.1.1-bin-hadoop2.7/python/pyspark/ml/__init__.py", line 22, in <module>
    from pyspark.ml.base import Estimator, Model, Transformer
  File "/usr/lib/spark/spark-2.1.1-bin-hadoop2.7/python/pyspark/ml/base.py", line 21, in <module>
    from pyspark.ml.param import Params
  File "/usr/lib/spark/spark-2.1.1-bin-hadoop2.7/python/pyspark/ml/param/__init__.py", line 26, in <module>
    import numpy as np
ImportError: No module named numpy
[ERROR] Command execution failed.
```
So... looks like this might be a compatibility issue. Numpy is installed.
Which numpy and Python versions are supported?
On my side:
numpy==1.13.0
python --version == Python 2.6.6
python3 --version == Python 3.4.5

**Comment by vruusmann** [comment]
The JPMML-SparkML package does not interact with the NumPy package in any way. The communication, if any, is mediated by the PySpark package.

Your `ImportError: No module named numpy` is raised by the PySpark package. So, you should open another issue in the PySpark (appears to be a submodule of Apache Spark) issue tracker.

**Comment by vruusmann** [comment]
Also, please update your local copy of the JPMML-SparkML-Package codebase to the `HEAD` version before filing any complaints. At the moment you're "troubleshooting" a legacy version (eg. on line 3 of `setup.py` there is no `from jpmml_sparkml import __license__, __version__` anymore).

**Comment by mrjoseph84** [comment]
I downloaded the jpmml-sparkml-package just couple of days ago so it looks like a new updates were released just recently. Whatever was the cause I see that the bug is now fixed - I removed the package and cloned the git repo again and... I could successfully build it.
