### ISSUE TITLE
java.lang.ClassNotFoundException: org.jpmml.sparkml.feature.NGramConverter

### ISSUE THREAD

**Issue by ergouzi23** [jpmml/jpmml-sparkml#39]
Hello,
I'm trying to use pmml export on a spark ml model  and I am getting a` java.lang.ClassNotFoundException `error when calling `ConverterUtil.toPMML`

I dealt with those conflicts by refering to readme.md and employing Maven Shade Plugin.

Here is my pom.xml file:
  ```
      <dependency>
			<groupId>org.jpmml</groupId>
			<artifactId>jpmml-sparkml</artifactId>
			<version>1.3.3</version>
			<scope>compile</scope>
    </dependency>

    <build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<excludes>
					<exclude>**/*.xml</exclude>
				</excludes>
				<filtering>true</filtering>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>net.alchim31.maven</groupId>
				<artifactId>scala-maven-plugin</artifactId>
				<version>3.2.1</version>
				<executions>
					<execution>
						<id>compile</id>
						<goals>
							<goal>compile</goal>
						</goals>
						<phase>process-resources</phase>
					</execution>
				</executions>
				<configuration>
					<scalaVersion>${scala.version}</scalaVersion>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>${maven.shade.version}</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<relocations>
								<relocation>
									<pattern>org.dmg.pmml</pattern>
									<shadedPattern>org.shaded.dmg.pmml</shadedPattern>
								</relocation>
								<relocation>
									<pattern>org.jpmml</pattern>
									<shadedPattern>org.shaded.jpmml</shadedPattern>
								</relocation>
							</relocations>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
```

Here is the error stack trace：
```
18/03/06 21:40:01 WARN sparkml.ConverterUtil: Failed to load transformer converter class
java.lang.ClassNotFoundException: org.jpmml.sparkml.feature.NGramConverter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.shaded.jpmml.sparkml.ConverterUtil.init(ConverterUtil.java:351)
	at org.shaded.jpmml.sparkml.ConverterUtil.init(ConverterUtil.java:318)
	at org.shaded.jpmml.sparkml.ConverterUtil.<clinit>(ConverterUtil.java:369)
	at com.nubia.train.Ad_ctr_train_PMML$.main(Ad_ctr_train_PMML.scala:157)
	at com.nubia.train.Ad_ctr_train_PMML.main(Ad_ctr_train_PMML.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
18/03/06 21:40:01 WARN sparkml.ConverterUtil: Failed to load transformer class
java.lang.ClassNotFoundException: org.apache.spark.ml.feature.MaxAbsScalerModel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.shaded.jpmml.sparkml.ConverterUtil.init(ConverterUtil.java:341)
	at org.shaded.jpmml.sparkml.ConverterUtil.init(ConverterUtil.java:318)
	at org.shaded.jpmml.sparkml.ConverterUtil.<clinit>(ConverterUtil.java:369)
	at com.nubia.train.Ad_ctr_train_PMML$.main(Ad_ctr_train_PMML.scala:157)
	at com.nubia.train.Ad_ctr_train_PMML.main(Ad_ctr_train_PMML.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
......
```
Is it because Maven Shade Plugin？
Thanks in advance :)

**Comment by vruusmann** [comment]
> java.lang.ClassNotFoundException: org.jpmml.sparkml.feature.NGramConverter

The README file currently suggests the following relocation pattern:
```xml
<relocation>
	<pattern>org.jpmml</pattern>
	<shadedPattern>org.shaded.jpmml</shadedPattern>
</relocation>
```

Depending on how you are packaging your application, it may be a bit too aggressive/greedy. Try to make it more specific by focussing on `org.jpmml.model` and `org.jpmml.schema` packages:
```xml
<relocation>
	<pattern>org.jpmml.model.</pattern>
	<shadedPattern>org.shaded.jpmml.model</shadedPattern>
</relocation>
<relocation>
	<pattern>org.jpmml.schema</pattern>
	<shadedPattern>org.shaded.jpmml.schema</shadedPattern>
</relocation>
```

I'm not taking any blame for the missing `org.apache.spark.ml.feature.MaxAbsScalerModel` class, though. Maybe this class is really missing in your Apache Spark version (was introduced in 2.0.X).

**Comment by ergouzi23** [comment]
I known the reason，my Spark version is 1.6.1.
Thank you so much for your explanation.

**Comment by vruusmann** [comment]
You need to work with JPMML-SparkML development branch `1.0-SNAPSHOT` when targeting Apache Spark ML 1.6.X:
https://github.com/jpmml/jpmml-sparkml/tree/1.0.X

The latest version appears to be `1.0.9`. Unfortunately, it doesn't support N-grams and other text model stuff.
