### ISSUE TITLE
Error: org.apache.spark.ml.feature.VectorAssembler is not supported

### ISSUE THREAD

**Issue by chinachenyadong** [jpmml/jpmml-sparkml#45]
I ran programs in spark-local sucessfully. But when I ran codes in spark-yarn online, the following error message occurred (I have shaded org.jpmml to org.shaded.jpmml):

    java.lang.IllegalArgumentException: Transformer class org.apache.spark.ml.feature.VectorAssembler is not supported
		at org.shaded.jpmml.sparkml.ConverterFactory.newConverter(ConverterFactory.java:53)
		at org.shaded.jpmml.sparkml.PMMLBuilder.build(PMMLBuilder.java:109)
		at com.iqiyi.columbus.joint_prevent.model.pmml.PMMLModelLocal$.saveModelAndEvaluate(PMMLModelLocal.scala:93)
		at com.iqiyi.columbus.joint_prevent.model.pmml.PMMLModelLocal$.main(PMMLModelLocal.scala:134)
		at com.iqiyi.columbus.joint_prevent.model.pmml.PMMLModelLocal.main(PMMLModelLocal.scala)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:635)
	
Here is the stages of PipelineModel and the codes of buliding pmml:
	val pipeline = new Pipeline().setStages(Array(vectorAssem, labelIndexer, featureIndexer, gbt, labelConverter))

	val pipelineModel = trainPipelineModel(data, trainingData)
    val pmml = new PMMLBuilder(schema, pipelineModel).build()

I used Spark 2.2.0, jpmml-sparkml 1.3.8, pmml-model 1.4.3(or 1.4.2, both failed).

**Comment by vruusmann** [comment]
> org.shaded.jpmml.sparkml.ConverterFactory

You have shaded all `org.jpmml.*` classes, but you should be shading ONLY `org.dmg.pmml.*` and `org.jpmml.model.*` classes.

At the moment JPMML-SparkML is trying to look up class `org.jpmml.sparkml.feature.VectorAssemblerConverter`, but it doesn't exist anymore, because you have renamed/repackaged it as `org.shaded.jpmml.sparkml.feature.VectorAssemblerConverter`.

Fix your build, or use my pre-packaged uber-JAR files:
https://github.com/jpmml/jpmml-sparkml/releases

**Comment by chinachenyadong** [comment]
It works, thank you so much~
