### ISSUE TITLE
Cant use spark's QuantileDiscretizer  for binning.

### ISSUE THREAD

**Issue by ChiranjeeviBhagavan** [jpmml/jpmml-sparkml#75]
Error Seen below :

Exception in thread "main" java.lang.NoSuchMethodError: org.dmg.pmml.Interval.setLeftMargin(Ljava/lang/Double;)Lorg/dmg/pmml/Interval;
	at org.jpmml.sparkml.feature.BucketizerConverter.encodeFeatures(BucketizerConverter.java:63)
	at org.jpmml.sparkml.FeatureConverter.registerFeatures(FeatureConverter.java:48)
	at org.jpmml.sparkml.PMMLBuilder.build(PMMLBuilder.java:110)

**Comment by vruusmann** [comment]
Fix your application classpath.

**Comment by ChiranjeeviBhagavan** [comment]
I was trying to generate a pmml file having QuantileDiscretizer in the pipeline. 
i was able to generate without this in pipeline though. Any more recommendations ?

**Comment by vruusmann** [comment]
> I was trying to generate a pmml file having QuantileDiscretizer in the pipeline.

Your application classpath is still wrong - the `QuantileDiscretizer` step simply makes it obvious.

> Any more recommendations?

See the README that corresponds to your Apache Spark version. The JPMML-SparkML repository contains multiple development branches, each for every supported Spache Spark version. If you apply 2.4.X instructions to 2.2.X or 2.3.X, you'll have trouble.
